### ISSUE TITLE
Bug with variable assigning when using memprof

### ISSUE THREAD

**Issue by tr1et** [jmdana/memprof#15] opened 2016-03-24 14:36 UTC
With this block of code:

```
...
print("Pre pos: " + str(start_point + i * unit_vector))
pos = start_point + i * unit_vector
print("Pos: " + str(pos))
...
```

Output when I run without "memprof":

```
Pre pos: (4.0, 0.0)
Pos: (4.0, 0.0)
```

But when I use "memprof":

```
Pre pos: (4.0, 0.0)


************
3s (+1s)
************
Pos: (4.0,)
```

See, the added vector is somehow not fully assigned - `Pos: (4.0,)` - _sometimes_ when using "memprof" and then a index out of range error later when I access it, without "memprof" the code working just fine. And it happen randomly in other similar blocks too.

I'm using Python 3.4, the vector class written by Mat Leonard [link](https://gist.github.com/mcleonard/5351452) (converted to Python 3), and compiled memprof with Visual C++ 2015 x64 instead of Visual C++ 2010 x86(maybe this is the problem, I don't know because I'm new to Python).

**Comment by jmdana** [comment] 2016-03-24 19:02
I understand that you are trying to use memprof under Windows, am I right? In principle, there is no reason why it shouldn't work, but it has never been tested in that platform. It could be something due to the compilation of cython (which is used by memprof) but, even if that is the case, it's very strange as memprof doesn't modify anything within your code.

I would suggest that you try to reproduce the error in a POSIX-compliant operating system (e.g. Linux or Mac OS X). Please let me know what is the outcome in any of those platforms.

**Comment by tr1et** [comment] 2016-03-24 19:37
Yes, I'm using Windows, and currently I don't have a Linux machine at hand to test, so may be later.

About the bug, somehow by adding some 'print' line before the assignment, I could _sometime_ fix the bug at that block. Sound really like a concurrency problem.

**Comment by jmdana** [comment] 2016-03-24 19:48
If you are using threads in your code it could be a race condition that you only see when using memprof. The memory profiling takes time and it could be slowing down one of the threads, making the problem more evident. 

Are you modifying the variables in a different thread? Are you using a mutex or any other kind of synchronisation mechanism?

**Comment by tr1et** [comment] 2016-03-25 07:32
No! It is just one python file run one function on one process, in fact I don't even know how to write multi-threaded python code yet . I just thought maybe "memprof" run on another thread and the bug happen on the interaction between "memprof" and my code.
It also is hard to recreate the bug, a simple for loop with a bunch of vector arithmetic (similar to the code) in it just profiled fine without problem. If I found anything new I will tell you.

**Comment by jmdana** [comment] 2017-05-06 14:44
@tr1et did you find anything new about this? Should we close the issue?

**Comment by tr1et** [comment] 2017-05-12 16:32
No, I didn't found anything else. You may close the project now, thank you!

**Closed** 2017-05-12 16:32 UTC
